
services:
  mariadb:
    build: ./requirments/mariadb
    image: mariadb
    container_name: mdb
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
  nginx:
    image: nginx
    container_name: nginx
    env_file: .env
    ports:
      - 9000:9000
    networks:
      - inception
    restart: always

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/data/wp-db

networks:
  inception:
    name: mmailanet