
services:
  mariadb:
    build: ./requirments/mariadb
    image: mariadb
    container_name: mdb
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
  nginx:
    build: ./requirments/nginx
    image: nginx
    container_name: nginx
    env_file: .env
    volumes:
      - wordpress:/var/www/html
    ports:
      - 443:443
    networks:
      - inception
    restart: always

volumes:
  mariadb:
    name: wp-db
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/data/wp-db
  wordpress:
    name: wp-files
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/data/wp-files

networks:
  inception:
    name: mmailanet