
services:
  mariadb:
    env_file: .env
    build: ./requirements/mariadb
    image: mariadb:v1
    container_name: mdb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
  nginx:
    depends_on:
      - wordpress
    env_file: .env
    build: ./requirements/nginx
    image: nginx:v1
    container_name: ngnx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  wordpress:
    depends_on:
      - mariadb
    env_file: .env
    build: ./requirements/wordpress
    image: wordpress:v1
    container_name: wp
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  redis:
    build: ./requirements/bonus/redis
    image: redis:v1
    container_name: rds
    networks:
      - inception
    restart: always

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:v1
    container_name: adm
    networks:
      - inception
    ports:
      - 8081:8080
    restart: always

  static-website:
    build: ./requirements/bonus/static-website
    image: static-website:v1
    container_name: web
    networks:
      - inception
    ports:
      - 8082:8080
    restart: always
  
  ftp:
    build: ./requirements/bonus/ftp
    image: ftp:v1
    container_name: ftp
    env_file: .env
    networks:
      - inception
    volumes:
      - wordpress:/wp
    ports:
      - "21:21"
      - "10000-10100:10000-10100"
    restart: always

  portainer:
    build: ./requirements/bonus/portainer
    image: portainer:v1
    container_name: prt
    env_file: .env
    volumes:
      - portainer:/port-data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - inception
    ports:
      - 4242:4242
    restart: always

networks:
  inception:
    name: mmailanet

volumes:
  mariadb:
    name: wp-db
    driver: local
    driver_opts:
      type: bind
      device: ~/data/wp-db
  wordpress:
    name: wp-files
    driver: local
    driver_opts:
      type: bind
      device: ~/data/wp-files
  portainer:
    name: port-data
    driver: local
    driver_opts:
      type: bind
      device: ~/data/port-data