
services:
  mariadb:
    env_file: .env
    build: ./requirements/mariadb
    image: mariadb:v1
    container_name: mdb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
  nginx:
    env_file: .env
    build: ./requirements/nginx
    image: nginx:v1
    container_name: ngnx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  wordpress:
    depends_on:
      - mariadb
    env_file: .env
    build: ./requirements/wordpress
    image: wordpress:v1
    container_name: wp
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  redis:
    build: ./requirements/bonus/redis
    image: redis:v1
    container_name: rds
    # volumes:
    #   - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer:v1
    container_name: adm
    networks:
      - inception
    ports:
      - 8081:8080
    restart: always

  static-website:
    build: ./requirements/bonus/static-website
    image: static-website:v1
    container_name: web
    networks:
      - inception
    ports:
      - 8082:8080
    restart: always

networks:
  inception:
    name: mmailanet

volumes:
  mariadb:
    name: wp-db
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/data/wp-db
  wordpress:
    name: wp-files
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/data/wp-files