
services:
  mariadb:
    env_file: .env
    build: ./requirments/mariadb
    image: mariadb:v1
    container_name: mdb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
  nginx:
    env_file: .env
    build: ./requirments/nginx
    image: nginx:v1
    container_name: ngnx
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

  wordpress:
    depends_on:
      - mariadb
    env_file: .env
    build: ./requirments/wordpress
    image: wordpress:v1
    container_name: wp
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    restart: always

networks:
  inception:
    name: mmailanet

volumes:
  mariadb:
    name: wp-db
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/data/wp-db
  wordpress:
    name: wp-files
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/data/wp-files